### ISSUE TITLE
ui patch workflow & local dev

### ISSUE THREAD

**Issue by Preskton** [Preskton/polyeffects-digit-ui#2]
- Seems to be a combo of https://github.com/polyeffects/digit_carla and https://github.com/polyeffects/digit_ui?
- `frontend` firmware updates contain files from both that can only be found in each (like `digit_ui.py` is only in `digit_carla`)
   - ~`digit_carla` might be old stuff - hasn't been updated in 3 years, and the systemd unit refs `show_widget.py` which is in `digit_ui`...?~ confirmed not needed from loki
   - `process_ui_messages()` appears to be main loop
   - maybe this is the original `Carla`? https://github.com/falkTX/Carla
- QT based frontend https://doc.qt.io/qtforpython/index.html
- UI files should end up in `/home/debian/UI`
- invoked by `polyui.service` with:
```
WorkingDirectory=/home/debian/UI
ExecStart=/usr/bin/python3 /home/debian/UI/show_widget.py -platform eglfs  -style /home/debian/UI/poly_style/
```
- eglfs is a QT 'platform' for embedded systems https://doc.qt.io/qt-6/embedded-linux.html
- python 3.7 based on deb

## todo

- [ ] confirm UI `overlay`
- [ ] identify dependencies, `pyenv` and `pipenv` to create reproducible environment
- [ ] identify how to run locally
- [ ] establish `Makefile` based on above

**Comment by Preskton** [comment]
python packages:

- `serd` - https://drobilla.net/files/pyserd_docs/
- `PySide2` - https://pypi.org/project/PySide2/
- `rdflib` - https://rdflib.readthedocs.io/en/stable/
- `rdfDICT` - https://pypi.org/project/RDFdict/

<img width="181" alt="image" src="https://user-images.githubusercontent.com/6252405/207068832-94b18a99-4b76-4084-aa86-37e6edcb8d0b.png">

**Comment by Preskton** [comment]
Pyside/QT version
```
>>> print(PySide2.__version__)
5.11.2
```

python 3.7.3rc1 -- will try with 3.7.11

**Comment by Preskton** [comment]
For `meson` -- do we need `ninja` --> https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-linux.zip

**Comment by Preskton** [comment]
serd @ `/usr/lib/python3/dist-packages/serd.cpython-37m-aarch64-linux-gnu.so`

**Comment by Preskton** [comment]
`/usr/lib/python3/dist-packages/serd.cpython-37m-aarch64-linux-gnu.so`
